auth_server: "auth"
fallback_server: "lobby"
disallow_connect_to_auth: true
server_unavailable_message: "§cНе удалось подключиться к вашему последнему серверу или лобби!"
auth_server_disallowed_message: "§cВы не можете подключаться обратно к серверу авторизации!"
kick_reason: "§cВы были отключены от сервера по причине: "